// Notification messages in every app language.
// The notification language follows the language chosen in the app (Menu > Language).
// A plan's own title is never translated: it is shown exactly as the user typed it.
//
// {festival} {emoji} {title} are filled in automatically.
// If a language is missing, English is used.

export const TEXTS = {
  en: {
    festivalHappyTitle: 'Happy {festival}! {emoji}',
    festivalHappyBody: 'Wishing you and your family a very happy {festival}. May this day bring you joy, peace and prosperity. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Today is {festival}. Wishing you peace and blessings. 🙏',
    weekTitle: '⏳ One week to go',
    weekBody: '{title} is in 7 days.',
    weekHidden: 'You have a private plan in 7 days.',
    todayTitle: '🎉 Today is the day!',
    todayBodyWish: "{title} — have you wished yet? Don't forget!",
    todayBodyGeneric: "{title} — don't forget!",
    todayHidden: 'You have a private plan today.',
    testTitle: '🔔 Notifications are working',
    testBody: 'You will get festival greetings and your plan reminders here.',
    tripSoonTitle: '🧳 Your trip starts in 1 hour',
    tripSoonBody: '{title} — {from} → {to}. Get ready!',
    tripNowTitle: '🚀 Time to start your trip!',
    tripNowBody: '{title} — {from} → {to}. Have a safe journey!',
  },
  hi: {
    festivalHappyTitle: '{festival} की हार्दिक शुभकामनाएँ! {emoji}',
    festivalHappyBody: 'आपको और आपके परिवार को {festival} की हार्दिक शुभकामनाएँ। यह दिन आपके जीवन में खुशियाँ, शांति और समृद्धि लाए। 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'आज {festival} है। आपको शांति और आशीर्वाद की शुभकामनाएँ। 🙏',
    weekTitle: '⏳ बस एक हफ़्ता बाकी',
    weekBody: '{title} — 7 दिन बाद है।',
    weekHidden: '7 दिन बाद आपका एक निजी प्लान है।',
    todayTitle: '🎉 आज वह दिन है!',
    todayBodyWish: '{title} — क्या आपने बधाई दी? भूलिएगा नहीं!',
    todayBodyGeneric: '{title} — भूलिएगा नहीं!',
    todayHidden: 'आज आपका एक निजी प्लान है।',
    testTitle: '🔔 नोटिफ़िकेशन चल रहे हैं',
    testBody: 'यहाँ आपको त्योहारों की शुभकामनाएँ और प्लान के रिमाइंडर मिलेंगे।',
    tripSoonTitle: '🧳 आपकी ट्रिप 1 घंटे में शुरू होगी',
    tripSoonBody: '{title} — {from} → {to}। तैयार हो जाइए!',
    tripNowTitle: '🚀 ट्रिप शुरू करने का समय!',
    tripNowBody: '{title} — {from} → {to}। यात्रा मंगलमय हो!',
  },
  zh: {
    festivalHappyTitle: '{festival}快乐！{emoji}',
    festivalHappyBody: '祝您和家人{festival}快乐！愿这一天带给您喜悦、平安与繁荣。🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: '今天是{festival}。愿您平安、蒙福。🙏',
    weekTitle: '⏳ 还有一周',
    weekBody: '{title} 还有7天。',
    weekHidden: '您有一个私人计划将在7天后到来。',
    todayTitle: '🎉 就是今天！',
    todayBodyWish: '{title} — 您送上祝福了吗？别忘了！',
    todayBodyGeneric: '{title} — 别忘了！',
    todayHidden: '您今天有一个私人计划。',
    testTitle: '🔔 通知运行正常',
    testBody: '您将在这里收到节日祝福和计划提醒。',
    tripSoonTitle: '🧳 您的旅行将在1小时后开始',
    tripSoonBody: '{title} — {from} → {to}。请做好准备！',
    tripNowTitle: '🚀 该出发了！',
    tripNowBody: '{title} — {from} → {to}。一路平安！',
  },
  es: {
    festivalHappyTitle: '¡Feliz {festival}! {emoji}',
    festivalHappyBody: 'Te deseo a ti y a tu familia un muy feliz {festival}. Que este día te traiga alegría, paz y prosperidad. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Hoy es {festival}. Te deseo paz y bendiciones. 🙏',
    weekTitle: '⏳ Falta una semana',
    weekBody: '{title} es en 7 días.',
    weekHidden: 'Tienes un plan privado en 7 días.',
    todayTitle: '🎉 ¡Hoy es el día!',
    todayBodyWish: '{title} — ¿ya felicitaste? ¡No lo olvides!',
    todayBodyGeneric: '{title} — ¡no lo olvides!',
    todayHidden: 'Tienes un plan privado hoy.',
    testTitle: '🔔 Las notificaciones funcionan',
    testBody: 'Aquí recibirás felicitaciones de festividades y recordatorios de tus planes.',
    tripSoonTitle: '🧳 Tu viaje empieza en 1 hora',
    tripSoonBody: '{title} — {from} → {to}. ¡Prepárate!',
    tripNowTitle: '🚀 ¡Es hora de empezar tu viaje!',
    tripNowBody: '{title} — {from} → {to}. ¡Buen viaje!',
  },
  ja: {
    festivalHappyTitle: '{festival}おめでとう！{emoji}',
    festivalHappyBody: 'あなたとご家族に、素敵な{festival}をお祈りします。喜びと平和と繁栄が訪れますように。🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: '今日は{festival}です。平和と祝福をお祈りします。🙏',
    weekTitle: '⏳ あと1週間',
    weekBody: '{title}まであと7日です。',
    weekHidden: '7日後に非公開の予定があります。',
    todayTitle: '🎉 いよいよ今日！',
    todayBodyWish: '{title} — もうお祝いしましたか？忘れずに！',
    todayBodyGeneric: '{title} — お忘れなく！',
    todayHidden: '今日は非公開の予定があります。',
    testTitle: '🔔 通知は正常に動作しています',
    testBody: 'お祝いのメッセージや予定のリマインダーがここに届きます。',
    tripSoonTitle: '🧳 旅行は1時間後に出発です',
    tripSoonBody: '{title} — {from} → {to}。準備しましょう！',
    tripNowTitle: '🚀 旅行の出発時間です！',
    tripNowBody: '{title} — {from} → {to}。どうぞお気をつけて！',
  },
  de: {
    festivalHappyTitle: 'Alles Gute zu {festival}! {emoji}',
    festivalHappyBody: 'Ich wünsche dir und deiner Familie Freude, Frieden und Wohlstand an diesem Tag ({festival}). 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Heute ist {festival}. Ich wünsche dir Frieden und Segen. 🙏',
    weekTitle: '⏳ Noch eine Woche',
    weekBody: '{title} ist in 7 Tagen.',
    weekHidden: 'Du hast in 7 Tagen einen privaten Plan.',
    todayTitle: '🎉 Heute ist es soweit!',
    todayBodyWish: '{title} — hast du schon gratuliert? Nicht vergessen!',
    todayBodyGeneric: '{title} — nicht vergessen!',
    todayHidden: 'Du hast heute einen privaten Plan.',
    testTitle: '🔔 Benachrichtigungen funktionieren',
    testBody: 'Hier erhältst du Festtagsgrüße und Erinnerungen an deine Pläne.',
    tripSoonTitle: '🧳 Deine Reise beginnt in 1 Stunde',
    tripSoonBody: '{title} — {from} → {to}. Mach dich bereit!',
    tripNowTitle: '🚀 Zeit, deine Reise zu starten!',
    tripNowBody: '{title} — {from} → {to}. Gute Reise!',
  },
  fr: {
    festivalHappyTitle: '{festival} – meilleurs vœux ! {emoji}',
    festivalHappyBody: 'Meilleurs vœux à vous et à votre famille pour {festival}. Que cette journée vous apporte joie, paix et prospérité. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Aujourd’hui, c’est {festival}. Je vous souhaite paix et bénédictions. 🙏',
    weekTitle: '⏳ Plus qu’une semaine',
    weekBody: '{title} dans 7 jours.',
    weekHidden: 'Vous avez un plan privé dans 7 jours.',
    todayTitle: '🎉 C’est aujourd’hui !',
    todayBodyWish: '{title} — avez-vous déjà envoyé vos vœux ? N’oubliez pas !',
    todayBodyGeneric: '{title} — n’oubliez pas !',
    todayHidden: 'Vous avez un plan privé aujourd’hui.',
    testTitle: '🔔 Les notifications fonctionnent',
    testBody: 'Vous recevrez ici les vœux des fêtes et les rappels de vos plans.',
    tripSoonTitle: '🧳 Votre voyage commence dans 1 heure',
    tripSoonBody: '{title} — {from} → {to}. Préparez-vous !',
    tripNowTitle: '🚀 C’est l’heure de partir !',
    tripNowBody: '{title} — {from} → {to}. Bon voyage !',
  },
  ar: {
    festivalHappyTitle: 'تهانينا بمناسبة {festival}! {emoji}',
    festivalHappyBody: 'أتمنى لك ولعائلتك يومًا مليئًا بالفرح والسلام والازدهار بمناسبة {festival}. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'اليوم هو {festival}. أتمنى لك السلام والبركات. 🙏',
    weekTitle: '⏳ بقي أسبوع واحد',
    weekBody: '{title} بعد 7 أيام.',
    weekHidden: 'لديك خطة خاصة بعد 7 أيام.',
    todayTitle: '🎉 اليوم هو الموعد!',
    todayBodyWish: '{title} — هل هنأت بعد؟ لا تنسَ!',
    todayBodyGeneric: '{title} — لا تنسَ!',
    todayHidden: 'لديك خطة خاصة اليوم.',
    testTitle: '🔔 الإشعارات تعمل',
    testBody: 'ستصلك هنا تهاني المناسبات وتذكيرات خططك.',
    tripSoonTitle: '🧳 رحلتك تبدأ بعد ساعة',
    tripSoonBody: '{title} — {from} → {to}. استعد!',
    tripNowTitle: '🚀 حان وقت بدء رحلتك!',
    tripNowBody: '{title} — {from} → {to}. رحلة سعيدة!',
  },
  ru: {
    festivalHappyTitle: 'С праздником — {festival}! {emoji}',
    festivalHappyBody: 'Желаю вам и вашей семье радости, мира и процветания в этот день — {festival}. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Сегодня {festival}. Желаю вам мира и благословений. 🙏',
    weekTitle: '⏳ Осталась неделя',
    weekBody: '{title} — через 7 дней.',
    weekHidden: 'Через 7 дней у вас личный план.',
    todayTitle: '🎉 Сегодня тот самый день!',
    todayBodyWish: '{title} — вы уже поздравили? Не забудьте!',
    todayBodyGeneric: '{title} — не забудьте!',
    todayHidden: 'Сегодня у вас личный план.',
    testTitle: '🔔 Уведомления работают',
    testBody: 'Здесь вы будете получать праздничные поздравления и напоминания о планах.',
    tripSoonTitle: '🧳 Ваша поездка начнётся через час',
    tripSoonBody: '{title} — {from} → {to}. Приготовьтесь!',
    tripNowTitle: '🚀 Пора отправляться!',
    tripNowBody: '{title} — {from} → {to}. Счастливого пути!',
  },
  pt: {
    festivalHappyTitle: 'Feliz {festival}! {emoji}',
    festivalHappyBody: 'Desejo a você e à sua família um dia cheio de alegria, paz e prosperidade em {festival}. 🌟',
    festivalRespectTitle: '{festival} {emoji}',
    festivalRespectBody: 'Hoje é {festival}. Desejo paz e bênçãos. 🙏',
    weekTitle: '⏳ Falta uma semana',
    weekBody: '{title} é em 7 dias.',
    weekHidden: 'Você tem um plano privado em 7 dias.',
    todayTitle: '🎉 Hoje é o dia!',
    todayBodyWish: '{title} — já deu os parabéns? Não esqueça!',
    todayBodyGeneric: '{title} — não esqueça!',
    todayHidden: 'Você tem um plano privado hoje.',
    testTitle: '🔔 As notificações estão funcionando',
    testBody: 'Você receberá aqui felicitações de festividades e lembretes dos seus planos.',
    tripSoonTitle: '🧳 Sua viagem começa em 1 hora',
    tripSoonBody: '{title} — {from} → {to}. Prepare-se!',
    tripNowTitle: '🚀 Hora de começar sua viagem!',
    tripNowBody: '{title} — {from} → {to}. Boa viagem!',
  },
};

export const fill = (template, values) =>
  template.replace(/\{(\w+)\}/g, (match, key) => (values[key] !== undefined ? values[key] : match));

export const getTexts = (lang) => ({ ...TEXTS.en, ...(TEXTS[lang] || {}) });
